numpy learned

In [3]:
import numpy as np

#### array creation routines

##### empty

In [3]:
# create empty array
a = np.empty((2,2), dtype=int, order='C')

In [5]:
a
# printed garbage array with shape 2,2 

array([[-1487872303,  -191182057],
       [ -278437194,  -451376276]])

##### empty like

In [10]:
# empty like
b = np.empty_like(a, dtype = float, shape=(1,4))

In [12]:
b
# created array like a with datatype float and shape = (1,4)

array([[0.00000000e+000, 9.61149019e-312, 9.61149020e-312,
        9.61149020e-312]])

##### eye

In [4]:
c = np.eye(5,3, k= -1, dtype= float, order='C')

In [6]:
c 
# created(5,3) array one on diagonal with -1 index of diagonal of float type

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

##### identity

In [9]:
np.identity(5, dtype=int)
# creates the identity square matrix with integer type

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

##### ones

In [11]:
np.ones((5,3), dtype=int, order='C')
# creates ones matrix of shape(5,3)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

##### zeroes

In [13]:
np.zeros((3,2), dtype=int)
# creates array of (3,2) dimensions of integer type

array([[0, 0],
       [0, 0],
       [0, 0]])

##### full

In [14]:
np.full((3,3), 3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [18]:
import random 
a = np.random.randint(1,9,9 ).reshape(3,3)
a

array([[6, 4, 2],
       [1, 4, 2],
       [8, 1, 2]])

In [21]:
np.full((3,3), a)

array([[6, 4, 2],
       [1, 4, 2],
       [8, 1, 2]])

In [23]:
np.full((3,3), [1,2,3])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [28]:
np.full((3,3), [1,2,3])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

##### range method on array

In [30]:
np.arange(1, 5, 0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [32]:
np.linspace(1, 5, 10, endpoint=True)
# finds evenly spaced 10 numbers between 1, 5 5 inclusive on a line

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])