numpy array manipulation

In [2]:
import numpy as np
import random 

In [4]:
a = np.random.randint(1, 9, 12).reshape(3,4)

In [5]:
a

array([[5, 7, 7, 7],
       [7, 6, 4, 4],
       [2, 4, 2, 4]])

getting shape of the array

In [6]:
a.shape

(3, 4)

changing the array shape

In [8]:
a.reshape(6,2)

array([[5, 7],
       [7, 7],
       [7, 6],
       [4, 4],
       [2, 4],
       [2, 4]])

In [10]:
a.ravel()
# returns contiguous flat array

array([5, 7, 7, 7, 7, 6, 4, 4, 2, 4, 2, 4])

In [16]:
a.flat[4]
# 1-D iterator over the array

7

In [18]:
a.flatten()
# returns copy of array in 1 D

array([5, 7, 7, 7, 7, 6, 4, 4, 2, 4, 2, 4])

transpose

In [21]:
a.transpose()

array([[5, 7, 2],
       [7, 6, 4],
       [7, 4, 2],
       [7, 4, 4]])

concatenate

In [22]:
b = np.random.randint(1, 9, 12).reshape(3,4)


In [24]:
np.concatenate((a,b), axis=0)

array([[5, 7, 7, 7],
       [7, 6, 4, 4],
       [2, 4, 2, 4],
       [4, 8, 6, 7],
       [7, 1, 3, 6],
       [8, 5, 8, 6]])

In [25]:
np.concatenate((a,b), axis=1)


array([[5, 7, 7, 7, 4, 8, 6, 7],
       [7, 6, 4, 4, 7, 1, 3, 6],
       [2, 4, 2, 4, 8, 5, 8, 6]])

In [26]:
a

array([[5, 7, 7, 7],
       [7, 6, 4, 4],
       [2, 4, 2, 4]])

In [29]:
np.delete(a, 0,0)

array([[7, 6, 4, 4],
       [2, 4, 2, 4]])

In [31]:
np.insert(a, 0, [1,1,1,1], axis=0)

array([[1, 1, 1, 1],
       [5, 7, 7, 7],
       [7, 6, 4, 4],
       [2, 4, 2, 4]])

In [32]:
np.resize(a, (5,5))

array([[5, 7, 7, 7, 7],
       [6, 4, 4, 2, 4],
       [2, 4, 5, 7, 7],
       [7, 7, 6, 4, 4],
       [2, 4, 2, 4, 5]])